### ISSUE TITLE
Create empty secret without google_secret_manager_secret_version

### ISSUE THREAD

**Issue by yoelmacia** [memes/terraform-google-secret-manager#18]
Hello and thank you for using my Secret Manager Terraform module. Please complete
this form to share your ideas. If you already have a proposed solution, open a
pull request for review and link it to this issue where prompted.

## Describe the feature

The module creates the version all the time, what will happen if we want to create an empty secret without google_secret_manager_secret_version.

## Acceptance criteria

Try to create a empty secret passing empty string to the var.secret but leads to validation check ( at least 1 character ), so why not have a count in the resource with a flag into variable empty secret.

```
variables secret_versioning {
  default = true 
}
```

```
resource "google_secret_manager_secret_version" "secret" {
  count       = var.secret_versioning ? 1 : 0
  secret      = google_secret_manager_secret.secret.id
  secret_data = var.secret
}
```

Use case: FOR EXAMPLE

```
module "gcp-secret" {
  source  = "memes/secret-manager/google"

  project_id = "testing"
  id            =  "${var.id}"
  secret     = ""
  secret_versioning = false
}
```

**Comment by memes** [comment]
Hello @yoelmacia, thanks for opening the issue.

Yeah, the existing constraint on `secret_data` is because the GCP API will not allow creating a version with an empty secret and I was not thinking of the use-case where someone wants to create a Secret Manager "slot" with possible IAM assignments, but manage/add versions separately from this module. That's an interesting case.

In that case, I think the more idiomatic change will be to allow an empty/null `secret_data` and skip version creation if it is empty. The change will be minor, I just need to make sure it handles the case where a version is managed outside the module.

**Comment by memes** [comment]
Postponing this to version 2.0.0; can't use a simple check for null/empty as it breaks the `random` module and any option changes should be in next major version. Will be working on that shortly now testing framework is in place.
