### ISSUE TITLE
google_secret_manager_secret "automatic" -> "auto"

### ISSUE THREAD

**Issue by cassus** [memes/terraform-google-secret-manager#76]
Hi! 

Thank for this great module!

## Describe the bug

With the new  5.0.0 google provider `[registry.terraform.io/hashicorp/google]` `automatic` was renamed to `auto`. The previous versions had a deprecation warning about this.

- See https://github.com/hashicorp/terraform-provider-google/pull/15859
- Deprecation message was: `automatic` is deprecated and will be removed in a future major release. Use `auto` instead.

```
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/db1_prod_socket_url/main.tf line 33, in resource "google_secret_manager_secret" "secret":
│   33:     automatic = length(var.replication) > 0 ? null : true
│ 
│ An argument named "automatic" is not expected here.
╵
```

**Comment by memes** [comment]
Hello @cassus, and thanks for the report. I've been seeing the deprecation for a while but haven't updated to v5 of Google provider yet because it has many changes that need to be tested across the TF modules I maintain. As a result, there will be a v2.1.2 release that enforces a '< 5' constraint and then a v2.2.0 release that has a '>= 5.0' constraint, after testing.

Related to #54
